### PR TITLE
[WIP] Add int suffix support, basic paren support and tests

### PR DESCRIPTION
**Pull request by jyapayne**
Adds basic support for integer suffixes in C.

### CODE REVIEW

**Comment by jyapayne** [comment]
Hmm, this needs quite a bit of work. There are a lot of cases to this parenthesis thing. Consider it a WIP PR :)

**Comment by genotrance** [comment]
Const is a mess since #defines can have some crazy stuff in there. Part of the reason why I removed expression parsing there. If you can get this working, will be awesome!

**Comment by awr1** [comment]
As a test case you may want to focus on cases of differing integer types in C used with coercion, e.g. `645635634896ull + -35436`

**Comment by jyapayne** [comment]
@awr1 thanks :) This is a rabbit hole lol

**Comment by jyapayne** [comment]
Closing this in favor of another PR that parses the treesitter nodes instead. PR will be coming soon

**Pull request closed without merging**
