### PR TITLE
Update cligen to latest version

### PR DESCRIPTION
**Pull request by zacharycarter**

### CODE REVIEW

**Comment by genotrance** [comment]
Any reason for this? I had back revved this for @disruptek.

**Comment by zacharycarter** [comment]
> Any reason for this? I had back revved this for @disruptek.

I guess it's not urgent - I just updated my project to use the latest version of cligen and nimble complains because I'm also relying on nimterop. What's the reason @disruptek wanted it reverted to 1.0?

**Comment by disruptek** [comment]
Don’t worry about me; Nimph used an old version because I needed to update the code to use a later version.  But that update has since been made.  👍

**Comment by disruptek** [comment]
But why require the latest version?  That’s just obnoxious.

**Comment by disruptek** [comment]
Wait, maybe this is a Nimble big.  Why would you have an issue with the existing requirement?

**Comment by genotrance** [comment]
@zacharycarter is this breaking you?

**Pull request closed without merging**
