### PR TITLE
[WIP] generate nim file to a nimout file instead of stdout, allowing to use stdout for logging, debugging etc; + other fixes

### PR DESCRIPTION
**Pull request by timotheecour**
* generate nim file to a nimout file instead of stdout,  allowing to use stdout for logging, debugging etc
* news utils.nim module (general purpose stuff that didn't belong in git.nim)

- [ ] TODO: handle windows correctly in removeFileStatic, existsFileStatic
- [ ] consider using shell script for random file creation at CT
on posix: mktemp
on windows: ?

- [ ]  [EDIT] just realized that os.fileExists can already be done at CT (and maybe a few other procs) so `nimterop/utils.nim` can be simplified ; eg no need for `existsFileStatic`

### CODE REVIEW

**Comment by genotrance** [comment]
I've totally revamped ast.nim so this might need some updates. Looks like most of your changes are outside ast.nim though.

**Comment by zevv** [comment]
Please use stderr for debug output

**Comment by kaushalmodi** [comment]
> generate nim file to a nimout file instead of stdout

+1

**Comment by timotheecour** [comment]
may re-open after rebase, later

**Pull request closed without merging**
