### PR TITLE
Fix single underscore error

### LINKED ISSUE #178: [Bug] Character constant '_' is not allowed
In the `checkIdentifier` proc, there is this line:

```nim
doAssert name[0] != '_' and name[^1] != '_', errmsg & " leading/trailing underscores '_'"
```

The problem is that if there is a constant in the C code that is just an underscore (ie `'_'`), this assert will fire.

### PR DESCRIPTION
**Pull request by jyapayne**
Fixes #178

### CODE REVIEW

**Comment by genotrance** [comment]
If `name == "_"`, what exactly does Nim do with the resulting identifier? Do we end up with an `_` identifier? Shouldn't it just be skipped by the user?

**Comment by jyapayne** [comment]
It's not an identifier that the issue. It's a character constant.

IE:

```c
typedef enum
{
    SDLK_UNDERSCORE = '_'
} SDL_KeyCode;
```

Nimterop thinks the nskConst here is an invalid identifier

**Comment by jyapayne** [comment]
And if you skip that symbol, you'll end up with an "Invalid character constant" error in Nim because

```nim
const SDLK_UNDERSCORE = ''.SDL_KeyCode
```

**Comment by jyapayne** [comment]
Maybe there's a better way to detect this?

**Comment by genotrance** [comment]
We are basically running into this since enums are scrubbed to check if they contain references to other identifiers which might need to run through `onSymbol()`. E.g. removing prefix `SDL_`.

Better to handle it in the caller in `getNimExpressions()`: https://github.com/nimterop/nimterop/blob/master/nimterop/getters.nim#L658 and also handle cases where you can have n `_` cause even `___` will fail.

Can you add a test case as well in `tnimterop_c.nim` / `test.h`. so that we can verify that it won't break in the future?

**Comment by jyapayne** [comment]
Hmm, you're right. I'll have to come up with a different solution. Not sure I'll have time though :(

**Pull request closed without merging**
